--Script de Criação
-- Tabela ENDERECO
CREATE TABLE ENDERECO (
    COD_END SERIAL PRIMARY KEY,
    LOGRADOURO VARCHAR(40),
    TIPO_LOG VARCHAR(40),
    COMPLEMENTO VARCHAR(20),
    CIDADE VARCHAR(60),
    UF CHAR(1),
    CEP CHAR(8),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(60)
);

-- Tabela PROFISSAO
CREATE TABLE PROFISSAO (
    COD_PROF SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    COD_CLI SERIAL PRIMARY KEY,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(60),
    TELEFONE VARCHAR(15),
    COD_PROF INT,
    FOREIGN KEY (COD_PROF) REFERENCES PROFISSAO(COD_PROF)
);

-- Tabela DEPENDENTE
CREATE TABLE DEPENDENTE (
    COD_CLI INT NOT NULL,
    COD_DEP SERIAL PRIMARY KEY,
    PARENTESCO VARCHAR(20),
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

-- Tabela CATEGORIA
CREATE TABLE CATEGORIA (
    COD_CAT SERIAL PRIMARY KEY,
    NOME VARCHAR(60),
    VALOR NUMERIC(15,2)
);

-- Tabela GENERO
CREATE TABLE GENERO (
    COD_GEN SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela FILMES
CREATE TABLE FILMES (
    COD_FILME SERIAL PRIMARY KEY,
    TITULO_ORIGINAL VARCHAR(100),
    TITULO VARCHAR(100),
    QUANTIDADE INT,
    COD_CAT INT,
    COD_GEN INT,
    FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT),
    FOREIGN KEY (COD_GEN) REFERENCES GENERO(COD_GEN)
);

-- Tabela LOCACAO
CREATE TABLE LOCACAO (
    COD_LOC SERIAL PRIMARY KEY,
    DATA_LOC DATE,
    DESCONTO NUMERIC(15,2),
    MULTA NUMERIC(15,2),
    SUB_TOTAL NUMERIC(15,2),
    COD_CLI INT,
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

-- Tabela LOCACAO_FILME
CREATE TABLE LOCACAO_FILME (
    COD_LOC INT NOT NULL,
    COD_FILME INT NOT NULL,
    QTD DIAS INT,
    DATA_DEVOL DATE,
    PRIMARY KEY (COD_LOC, COD_FILME),
    FOREIGN KEY (COD_LOC) REFERENCES LOCACAO(COD_LOC),
    FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
);

-- Tabela ATOR
CREATE TABLE ATOR (
    COD_ATOR SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela FILME_ATOR
CREATE TABLE FILME_ATOR (
    COD_ATOR INT NOT NULL,
    COD_FILME INT NOT NULL,
    ATOR CHAR(1),
    DIRETOR CHAR(1),
    PRIMARY KEY (COD_ATOR, COD_FILME),
    FOREIGN KEY (COD_ATOR) REFERENCES ATOR(COD_ATOR),
    FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
);

-- Tabela CLI_ENDERECO
CREATE TABLE CLI_ENDERECO (
    COD_END INT NOT NULL,
    COD_CLI INT NOT NULL,
    PRIMARY KEY (COD_END, COD_CLI),
    FOREIGN KEY (COD_END) REFERENCES ENDERECO(COD_END),
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);


--Script de Inserção
-- Inserindo dados na tabela PROFISSAO
INSERT INTO PROFISSAO (NOME) VALUES ('Advogado'), ('Médico'), ('Professor');

-- Inserindo dados na tabela CLIENTE
INSERT INTO CLIENTE (CPF, NOME, TELEFONE, COD_PROF) VALUES 
('12345678901', 'João Fox', '212121212', 1),
('12345678902', 'Martha Rocha', '222222222', 2),
('12345678903', 'marina da Silva', '232323232', 3);

-- Inserindo dados na tabela ENDERECO
INSERT INTO ENDERECO (LOGRADOURO, TIPO_LOG, COMPLEMENTO, CIDADE, UF, CEP, NUMERO, BAIRRO) VALUES 
('RUA ABA', 'Rua', 'Apt 101', 'SÃO PAULO', 'SP', '12345678', '10', 'Centro'),
('AVENIDA BOLIVIA', 'Avenida', 'Casa', 'CAMPINAS', 'SP', '23456789', '20', 'Bairro B'),
('TRAVESSA DUARTE', 'Travessa', 'Bloco 3', 'BRASILIA', 'DF', '34567890', '30', 'Bairro C');

-- Inserindo dados na tabela CLI_ENDERECO
INSERT INTO CLI_ENDERECO (COD_END, COD_CLI) VALUES (1, 1), (2, 2), (3, 3);

-- Inserindo dados na tabela DEPENDENTE
INSERT INTO DEPENDENTE (COD_CLI, PARENTESCO) VALUES 
(1, 'Filho'),
(2, 'Esposa'),
(3, 'Filha');

-- Inserindo dados na tabela CATEGORIA
INSERT INTO CATEGORIA (NOME, VALOR) VALUES ('Ação', 15.00), ('Comédia', 12.00), ('Ação', 10.00);

-- Inserindo dados na tabela GENERO
INSERT INTO GENERO (NOME) VALUES ('Aventura'), ('Romance'), ('Aventura');

-- Inserindo dados na tabela FILMES
INSERT INTO FILMES (TITULO_ORIGINAL, TITULO, QUANTIDADE, COD_CAT, COD_GEN) VALUES 
('Superman: the Movie', 'Super Man', 10, 1, 1),
('City of Angel', 'Cidade dos Anjos', 5, 2, 2),
('Wonder Woman', 'Mulher Maravilha', 7, 3, 3);

-- Inserindo dados na tabela LOCACAO
INSERT INTO LOCACAO (DATA_LOC, DESCONTO, MULTA, SUB_TOTAL, COD_CLI) VALUES 
('2024-06-01', 5.00, 0.00, 50.00, 1),
('2024-06-10', 0.00, 10.00, 30.00, 2),
('2024-06-15', 3.00, 0.00, 40.00, 3);

-- Inserindo dados na tabela LOCACAO_FILME
INSERT INTO LOCACAO_FILME (COD_LOC, COD_FILME, QTD, DATA_DEVOL) VALUES 
(1, 1, 3, '2024-06-05'),
(2, 2, 5, '2024-06-18'),
(3, 3, 7, '2024-06-22');

-- Inserindo dados na tabela ATOR
INSERT INTO ATOR (NOME) VALUES ('HENRY CAVILL'), ('NICOLAS CAGE'), ('GAL GADOT');

-- Inserindo dados na tabela FILME_ATOR
INSERT INTO FILME_ATOR (COD_ATOR, COD_FILME, ATOR, DIRETOR) VALUES 
(1, 1, 'S', 'N'),
(2, 2, 'S', 'N'),
(3, 3, 'S', 'N');

