CREATE TABLE ENDERECO (
    COD_END SERIAL PRIMARY KEY,
    LOGRADOURO VARCHAR(40),
    TIPO_LOG VARCHAR(40),
    COMPLEMENTO VARCHAR(20),
    CIDADE VARCHAR(60),
    UF CHAR(2),
    CEP CHAR(8),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(60)
);

CREATE TABLE PROFISSAO (
    COD_PROF SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

CREATE TABLE CLIENTE (
    COD_CLI SERIAL PRIMARY KEY,
    CPF CHAR(11),
    NOME VARCHAR(60),
    TELEFONE VARCHAR(15),
    COD_PROF INT REFERENCES PROFISSAO(COD_PROF)
);

CREATE TABLE CLI_ENDERECO (
    COD_END INT REFERENCES ENDERECO(COD_END),
    COD_CLI INT REFERENCES CLIENTE(COD_CLI),
    PRIMARY KEY (COD_END, COD_CLI)
);

CREATE TABLE DEPENDENTE (
    COD_CLI INT REFERENCES CLIENTE(COD_CLI),
    COD_DEP INT,
    PARENTESCO VARCHAR(20),
    PRIMARY KEY (COD_CLI, COD_DEP)
);

CREATE TABLE CATEGORIA (
    COD_CAT SERIAL PRIMARY KEY,
    NOME VARCHAR(60),
    VALOR NUMERIC(15, 2)
);

CREATE TABLE GENERO (
    COD_GEN SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

CREATE TABLE FILMES (
    COD_FILME SERIAL PRIMARY KEY,
    TITULO_ORIGINAL VARCHAR(100),
    TITULO VARCHAR(100),
    QUANTIDADE INT,
    COD_CAT INT REFERENCES CATEGORIA(COD_CAT),
    COD_GEN INT REFERENCES GENERO(COD_GEN)
);

CREATE TABLE LOCACAO (
    COD_LOC SERIAL PRIMARY KEY,
    DATA_LOC DATE,
    DESCONTO NUMERIC(15, 2),
    MULTA NUMERIC(15, 2),
    SUB_TOTAL NUMERIC(15, 2),
    COD_CLI INT REFERENCES CLIENTE(COD_CLI)
);

CREATE TABLE LOCACAO_FILME (
    COD_LOC INT REFERENCES LOCACAO(COD_LOC),
    COD_FILME INT REFERENCES FILMES(COD_FILME),
    NUM_DIAS INT,
    DATA_DEVOL DATE,
    PRIMARY KEY (COD_LOC, COD_FILME)
);

CREATE TABLE ATOR (
    COD_ATOR SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

CREATE TABLE FILME_ATOR (
    COD_ATOR INT REFERENCES ATOR(COD_ATOR),
    COD_FILME INT REFERENCES FILMES(COD_FILME),
    DIRETOR CHAR(1),
    PRIMARY KEY (COD_ATOR, COD_FILME)
);
